#!/bin/bash -ue

if [[ -z "$ACTION" ]]; then
	echo "This tool is meant to be run by udev. See https://github.com/faxm0dem/kwap" >&2
	exit 2
fi

opts=$(getopt -o i:x:d: --long internal:,xauthority:,display:: -n 'option-parser' -- "$@")
eval set -- "$opts"

function help {
	echo "Usage:
	  $0 <--internal 15> <--xauthority ~/Xauthority> [--display]
		$0 <-i 'AT Translated Set 2 keyboard'>"
	exit 1
}

function get_core_keyboard_id {
	xinput list --short|awk -F[=\[] '/master keyboard/{print $2}'
}

if [[ "$1" == "--" ]]; then help; fi

while true; do
	case "$1" in
		--internal|-i)
			case "$2" in
				"") help;;
				*) INT_KEYBOARD_ID="$2"; shift 2;;
			esac;;
		--xauthority|-x)
			case "$2" in
				"") help;;
				*) export XAUTHORITY="$2"; shift 2;;
			esac;;
		--display|-d)
			case "$2" in
				"") shift 2;;
				*) export DISPLAY="$2"; shift 2;;
			esac;;
		--) shift; break;;
		-h|--help) help;;
		*) echo "Argument parsing error" >&2; break;;
	esac
done

if [ "${ACTION}" = "add" -a -d "/sys${DEVPATH}" ]; then
	logger -t kwap external keyboard $DEVPATH connected
	xinput --disable "$INT_KEYBOARD_ID"
elif [[ "${ACTION}" == "remove" ]]; then
	logger -t kwap external keyboard $DEVPATH disconnected
	xinput --enable "$INT_KEYBOARD_ID"
fi

